version: 2.1
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: bcel-util-gradle-cache-v1-{{ checksum "build.gradle" }}

      - run: ./gradlew build

      - save_cache: # saves the project dependencies
          paths:
            - ~/.gradle
          key: bcel-util-gradle-cache-v1-{{ checksum "pom.xml" }}

      - run: ./gradlew build
